import React, { Suspense, useEffect, useMemo, useRef, useState } from 'react'
import { Canvas, useFrame, useThree } from '@react-three/fiber'
import { ContactShadows, Environment, Float, Html, MeshReflectorMaterial, RoundedBox, Sparkles, Text } from '@react-three/drei'
import * as THREE from 'three'

const rooms = [
  { id: 0, code: '01', name: 'THE ATRIUM', subtitle: 'A world begins with a threshold.', camera: [0, 2.2, 9.5], target: [0, 1.4, 0], accent: '#cfff42' },
  { id: 1, code: '02', name: 'CHROMA HALL', subtitle: 'Colour becomes a navigable material.', camera: [-8.5, 2.3, 3.6], target: [-5, 1.5, 0], accent: '#ff725b' },
  { id: 2, code: '03', name: 'ORBIT ROOM', subtitle: 'Objects hold their own gravity.', camera: [8.6, 2.4, 3.6], target: [5, 1.45, 0], accent: '#93b4ff' },
]

function ArtObject({ position, color, type = 'orb', title, onSelect }) {
  const ref = useRef(); const [hovered, setHovered] = useState(false)
  useFrame((state) => { if (ref.current) { ref.current.rotation.y += .003; ref.current.position.y = position[1] + Math.sin(state.clock.elapsedTime * 1.25 + position[0]) * .08 } })
  return <group position={position} ref={ref} onClick={(e) => { e.stopPropagation(); onSelect({ title, color, type }) }} onPointerOver={(e) => { e.stopPropagation(); setHovered(true); document.body.style.cursor = 'pointer' }} onPointerOut={() => { setHovered(false); document.body.style.cursor = 'auto' }}>
    <mesh scale={hovered ? 1.12 : 1} castShadow>{type === 'orb' ? <icosahedronGeometry args={[.85, 3]} /> : type === 'arch' ? <torusGeometry args={[.82, .27, 20, 48, Math.PI]} /> : <octahedronGeometry args={[.95, 1]} />}<meshStandardMaterial color={color} emissive={color} emissiveIntensity={hovered ? .42 : .12} roughness={.18} metalness={.52} /></mesh>
    {hovered && <Html center distanceFactor={10}><div className="object-tag">CLICK TO INSPECT</div></Html>}
  </group>
}

function Gateway({ position, rotation = [0, 0, 0], color, label, direction, onMove }) {
  const [hovered, setHovered] = useState(false)
  return <group position={position} rotation={rotation}><RoundedBox args={[2.25, 3.85, .32]} radius={.2} smoothness={5}><meshStandardMaterial color={color} roughness={.45} /></RoundedBox><RoundedBox args={[1.48, 3.05, .4]} radius={.7} smoothness={5} position={[0, -.3, -.02]}><meshStandardMaterial color="#131613" roughness={.7} /></RoundedBox><mesh position={[0, -.3, .22]} onClick={(e) => { e.stopPropagation(); onMove(direction) }} onPointerOver={() => { setHovered(true); document.body.style.cursor = 'pointer' }} onPointerOut={() => { setHovered(false); document.body.style.cursor = 'auto' }}><circleGeometry args={[.5, 36]} /><meshBasicMaterial color={hovered ? '#ffffff' : color} transparent opacity={hovered ? 1 : .78} /></mesh><Text position={[0, -.32, .25]} fontSize={.46} color="#151614" anchorX="center" anchorY="middle">{direction === 'next' ? '→' : '←'}</Text><Text position={[0, -2.12, .18]} fontSize={.12} color="#e8e8df" anchorX="center">{label}</Text></group>
}

function CameraRig({ room }) { const { camera } = useThree(); const lookAt = useMemo(() => new THREE.Vector3(), []); useFrame(() => { camera.position.lerp(new THREE.Vector3(...room.camera), .035); lookAt.lerp(new THREE.Vector3(...room.target), .04); camera.lookAt(lookAt) }); return null }

function World({ room, onMove, onSelect }) { return <><CameraRig room={room} /><color attach="background" args={['#111310']} /><fog attach="fog" args={['#111310', 8, 22]} /><ambientLight intensity={.42} /><spotLight position={[0, 7, 3]} angle={.55} penumbra={1} intensity={170} color="#fff9df" castShadow /><pointLight position={[-4, 2.6, 1]} intensity={22} color="#cfff42" /><pointLight position={[4, 2.6, 1]} intensity={18} color="#ff725b" /><mesh rotation={[-Math.PI / 2, 0, 0]} receiveShadow><planeGeometry args={[42, 28]} /><MeshReflectorMaterial blur={[300, 90]} resolution={1024} mixBlur={1} mixStrength={15} roughness={.82} color="#242721" metalness={.25} /></mesh><mesh position={[0, 3.15, -3.1]}><planeGeometry args={[4.7, 1.15]} /><meshBasicMaterial color="#eeede6" /><Text position={[0, 0, .02]} fontSize={.3} color="#111310" anchorX="center">YNGCOMPANY / SPATIAL STUDIES</Text></mesh><Text position={[0, 2.33, -3.06]} fontSize={.12} color="#d4ff45" anchorX="center">INTERACTIVE EXHIBITION · 2026</Text><Gateway position={[-4.95, .45, -1.1]} rotation={[0, .17, 0]} color="#ff725b" label="CHROMA HALL" direction="prev" onMove={onMove} /><Gateway position={[4.95, .45, -1.1]} rotation={[0, -.17, 0]} color="#93b4ff" label="ORBIT ROOM" direction="next" onMove={onMove} /><Float speed={1.5} rotationIntensity={.13} floatIntensity={.24}><ArtObject position={[0, 1.3, .2]} color={room.accent} title={room.id === 0 ? 'LUMEN / 01' : room.id === 1 ? 'CHROMA / 02' : 'ORBIT / 03'} type={room.id === 1 ? 'arch' : room.id === 2 ? 'crystal' : 'orb'} onSelect={onSelect} /></Float><ArtObject position={[-5, 1.22, 0]} color="#ff725b" title="CORAL MONOLITH" type="arch" onSelect={onSelect} /><ArtObject position={[5, 1.15, 0]} color="#93b4ff" title="BLUE FREQUENCY" type="crystal" onSelect={onSelect} /><Sparkles count={95} scale={[17, 5, 10]} size={1.25} speed={.22} color={room.accent} /><ContactShadows position={[0, .02, 0]} opacity={.58} scale={20} blur={2.4} far={5} /><Environment preset="warehouse" /></> }

export default function SpatialExperience() {
  const [active, setActive] = useState(0); const [selected, setSelected] = useState(null); const room = rooms[active]; const move = (direction) => setActive((current) => direction === 'next' ? (current + 1) % rooms.length : (current + rooms.length - 1) % rooms.length)
  useEffect(() => { const keyMove = (event) => { if (event.key === 'ArrowRight') move('next'); if (event.key === 'ArrowLeft') move('prev'); if (event.key === 'Escape') setSelected(null) }; window.addEventListener('keydown', keyMove); return () => window.removeEventListener('keydown', keyMove) }, [])
  return <main className="experience"><Canvas shadows dpr={[1, 2]} camera={{ position: room.camera, fov: 48 }} onPointerMissed={() => setSelected(null)}><Suspense fallback={null}><World room={room} onMove={move} onSelect={setSelected} /></Suspense></Canvas><header className="experience-nav"><a className="spatial-brand" href="#top"><span>Y</span><b>YNGCOMPANY</b><small>SPATIAL STUDIES</small></a><div className="nav-center">WEBGL EXPERIENCE <i>✦</i> VOL. 01</div><button className="sound" onClick={() => alert('Sound design is planned for the production version.')}>SOUND <span>○</span></button></header><section className="scene-copy"><p className="scene-index">{room.code} / 03</p><h1>{room.name.split(' ').map((word, index) => <React.Fragment key={word}>{index > 0 && <br />}{word}</React.Fragment>)}</h1><p>{room.subtitle}</p></section><div className="scene-hud"><span>CLICK OBJECTS TO INSPECT</span><span>DRAG / ARROWS TO NAVIGATE</span></div><nav className="navigation"><button aria-label="Previous room" onClick={() => move('prev')}>←</button><div className="room-dots">{rooms.map((item) => <button key={item.id} className={item.id === active ? 'active' : ''} aria-label={`Go to ${item.name}`} onClick={() => setActive(item.id)}><i style={{ background: item.accent }} /></button>)}</div><button aria-label="Next room" onClick={() => move('next')}>→</button></nav><aside className="tech-card"><span>BUILT WITH</span><b>THREE.JS</b><p>React Three Fiber · Raycasting · Dynamic camera choreography · Real-time lighting</p></aside>{selected && <div className="inspect-panel"><button onClick={() => setSelected(null)}>×</button><span>SELECTED ARTIFACT</span><h2>{selected.title}</h2><p>This object uses raycast interaction, material response and frame-based animation within a real-time Three.js scene.</p><div style={{ background: selected.color }} /></div>}<div className="mobile-hint">SWIPE OR USE THE ARROWS</div></main>
}
